% routine for generating the following figures (and possibly save them)

% 1.1 - 1.2
% profit V MLE - (only better than random)
% 2.1 - 2.2
% profit V alpha - "
% 3.1 - 3.2
% profit V gamma - "
% 4.1 - 4.2
% profit V beta - "
% 5
% profit V alpha V gamma

tic;
clear
close all;                  % there is another close all (to close figs generated by grad_desc_comparison()
SIGNIFICANCE_THRESHOLD = 0; % threshold for considering players better than scrambled (0 all players, 0.5 above chance (same as scrabled))
SAVE_FIG = 0;               % flag to handle figure saving on disk (0 does NOT save figures, 1 saves figures)
FIGURES = [0,0,0,0,1];      % boolean vector of flags for figures 
                            % [profit V MLE, profit V alpha, profit V gamma, profit V beta, profit V alpha V gamma]

%COMPARISON_FACTOR = 0.01;   % tolerance level
CHANCE_THRESHOLD = 0.5;     % probability threshold for chance 
MLE_THRESHOLD = 10;         % consider only players who are RL (arbitrary choice, highest [23.288897]) %TODO check if this still holds after graddesc
P_VALUE_THRESHOLD = 0.05;   % p-value threshold

% markup for figures
dx = 0.25;                  % shift for the player numbers on the datapoints
dy = 0.01;
FONT_SIZE = 30;             
ID_TEXT_SIZE = 20;
PRINT_WIDTH = 80;
PRINT_HEIGHT = 50;
MARKER_SIZE = 100;

RESTRICTED = 0;
ALGORITHM = 'qlearning';
CAP = 107;  % alternative 25
N_ACTIONS = 3;
RISK_MEASURE = 'beta'; % alternative risk

% load model results
% [playerID alpha beta gamma MLE randomMLE transactions]
[better_than_random,model,ng_better_than_random,noGamma] = grad_desc_comparison(RESTRICTED,ALGORITHM,CAP,N_ACTIONS,RISK_MEASURE,0);
close all;

% load performances 
performances = csvread('../data/profit_performances.csv');

% get the number of players
playerAmount = size(performances,1);

% stats for all players (comparison performance v MLE)
% [ID, alpha, beta, gamma, MLE, randMLE, transactions_number profit_performance]
stats_all =  [model, performances(:,2)];
% stats for only those players who are full RL 
% index+1 because better_than_random 1st col are IDs and start from 0
stats_full = [better_than_random, performances(better_than_random(:,1)+1,2)];
% stats for only those players who are nogamma 
stats_ng =   [ng_better_than_random, performances(ng_better_than_random(:,1)+1,2)];


% sort players according to performances 
% all players (including non RL)
ranked_performances = sortrows(stats_all,8);
% players ids (+1 to be consistent with the paper correction)
labels = num2str(ranked_performances(:,1)+1);

% better than random (stats_ng or stats_full)
btr_ranked_performances = sortrows(stats_ng,8);
% players ids
btr_labels = num2str(btr_ranked_performances(:,1));

% on the x-axis there is profit
x = ranked_performances(:,8);
btr_x = btr_ranked_performances(:,8);

%% FIGURE 1 profit VS MLE
if FIGURES(1)

    

    % on the y-axis there is MLE (best and random) normalised
    % over the number of transactions
    y_best = ranked_performances(:,5)./ranked_performances(:,7);
    y_random = ranked_performances(:,6)./ranked_performances(:,7);

   
    % calculate regression coefficient R and p-value
    [R,P]=corrcoef(x,y_best);

    fig1_1 = figure();
    hold on;

    % plot players MLE vs profit
    scatter(x, y_best,MARKER_SIZE, 'bo');
    
    % draw the regression line
    lsline;
    
    % plot their ID (+1 for consistency with paper correction)
    text(x + dx, y_best+dy ,labels,'FontSize',ID_TEXT_SIZE);

    % plot line for random MLE 
    plot(x,y_random,'r-');

    % title, labels, font
    title_text = ['Performance VS MLE - R = ',num2str(R(1,2))];
    title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);
    disp(title_text);
    ylabel('Model Fitness (MLE) norm. on # of trans.');
    xlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);
    axis([min(x)+min(x) max(x)-min(x) 0 1.2])
    hold off

    if SAVE_FIG
        set(gcf, 'PaperUnits', 'centimeters');
        set(gcf, 'PaperPosition', [0 0 PRINT_WIDTH PRINT_HEIGHT]);
        path = '../graphs/stats/performance_cloud/';
        fileName = [path, 'performance_vs_MLE_restr',num2str(RESTRICTED)];
        fileName = [fileName,'_',ALGORITHM];
        fileName = [fileName,'_CAP',num2str(CAP),'_nAct',num2str(N_ACTIONS),'.png'];
        print(fig1_1, '-dpng', '-loose', fileName); 
    end
    
    %% FIG 1.2

    % on the y-axis there is MLE (best and random) normalised
    % over the number of transactions
    y_best = btr_ranked_performances(:,5)./btr_ranked_performances(:,7);
    y_random = btr_ranked_performances(:,6)./btr_ranked_performances(:,7);

    % calculate regression coefficient R and p-value
    [R,P]=corrcoef(btr_x,y_best);

    fig1_2 = figure();
    hold on;

    % plot players MLE vs profit
    scatter(btr_x, y_best,MARKER_SIZE, 'bo');
    text(btr_x + dx, y_best+dy ,btr_labels,'FontSize',ID_TEXT_SIZE);

    % plot line for random MLE 
    plot(btr_x,y_random,'rd');

    % draw the regression line
    lsline;

    % title, labels, font
    title_text = ['Performance VS MLE - R = ',num2str(R(1,2))];
    title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);
    disp(title_text);
    ylabel('Model Fitness (MLE)');
    xlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);
    axis([min(x)+min(x) max(x)-min(x) 0 1.2])
    
    hold off
end


%% FIGURE 2 profit VS alpha
if FIGURES(2)

    
    % on the y-axis there is alpha 
    y_alpha = ranked_performances(:,2);
    [R,P]=corrcoef(x,y_alpha);

    fig2_1 =figure();
    hold on;

    % plot alpha vs profit
    scatter(x, y_alpha,MARKER_SIZE, 'bo');
    text(x + dx/10, y_alpha + dy/10 ,labels,'FontSize',ID_TEXT_SIZE);

    % draw the regression line
    lsline;

    % title, labels, font
    title_text = ['Performance VS alpha - R = ',num2str(R(1,2))];
    title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);
    ylabel('Alpha');
    xlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);
    axis([min(x)+min(x) max(x)-min(x) -0.1 2.1])
    hold off;
    if SAVE_FIG
        set(gcf, 'PaperUnits', 'centimeters');
        set(gcf, 'PaperPosition', [0 0 PRINT_WIDTH PRINT_HEIGHT]);
        path = '../graphs/stats/performance_cloud/';
        fileName = [path, 'performance_vs_alpha_restr',num2str(RESTRICTED)];
        fileName = [fileName,'_',ALGORITHM];
        fileName = [fileName,'_CAP',num2str(CAP),'_nAct',num2str(N_ACTIONS),'.png'];
        print(fig2_1, '-dpng', '-loose', fileName); 
    end
    
    %% FIG 2.2

    % on the y-axis there is alpha 
    btr_y_alpha = btr_ranked_performances(:,2);

    % calculate regression coefficient R and p-value
    [R,P]=corrcoef(btr_x,btr_y_alpha);

    fig2_2 = figure();
    hold on;

    % plot players MLE vs profit
    scatter(btr_x, btr_y_alpha,MARKER_SIZE, 'bo');
    text(btr_x + dx, btr_y_alpha+dy ,btr_labels,'FontSize',ID_TEXT_SIZE);

    % draw the regression line
    lsline;

    % title, labels, font
    title_text = ['Performance VS alpha - R = ',num2str(R(1,2))];
    title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);
    disp(title_text);
    ylabel('Alpha');
    xlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);
    axis([min(x)+min(x) max(x)-min(x) -0.1 2.1])
    hold off
end

%% FIGURE 3 profit VS gamma 
if FIGURES(3)
    % on the y-axis there is gamma 
    % 0 gamma for players whose RL model is not SS better than NG
    y_gamma = ranked_performances(:,4);
    [R,P]=corrcoef(x,y_gamma);

    fig3_1= figure();
    hold on;

    % plot gamma vs profit
    scatter(x, y_gamma,MARKER_SIZE, 'bo');
    text(x + dx/10, y_gamma + dy/10 ,labels,'FontSize',ID_TEXT_SIZE);

    % draw the regression line
    lsline;

    % title, labels, font
    title_text = ['Performance VS gamma - R = ',num2str(R(1,2))];
    title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);
    ylabel('Gamma');
    xlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);
    axis([min(x)+min(x) max(x)-min(x) -0.1 2.1])
    
    hold off;
    if SAVE_FIG
        set(gcf, 'PaperUnits', 'centimeters');
        set(gcf, 'PaperPosition', [0 0 PRINT_WIDTH PRINT_HEIGHT]);
        path = '../graphs/stats/performance_cloud/';
        fileName = [path, 'performance_vs_gamma_restr',num2str(RESTRICTED)];
        fileName = [fileName,'_',ALGORITHM];
        fileName = [fileName,'_CAP',num2str(CAP),'_nAct',num2str(N_ACTIONS),'.png'];
        print(fig3_1, '-dpng', '-loose', fileName); 
    end
    
    %% FIG 3.2

    % on the y-axis there is alpha 
    btr_y_gamma = btr_ranked_performances(:,4);

    % calculate regression coefficient R and p-value
    [R,P]=corrcoef(btr_x,btr_y_gamma);

    fig3_2 = figure();
    hold on;

    % plot players MLE vs profit
    scatter(btr_x, btr_y_gamma,MARKER_SIZE, 'bo');
    text(btr_x + dx, btr_y_gamma+dy ,btr_labels,'FontSize',ID_TEXT_SIZE);

    % draw the regression line
    lsline;

    % title, labels, font
    title_text = ['Performance VS gamma - R = ',num2str(R(1,2))];
    title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);
    disp(title_text);
    ylabel('Gamma');
    xlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);

    hold off
end

%% FIGURE 4 profit VS beta 
if FIGURES(4)
    % on the y-axis there is beta 
    % 0 gamma for players whose RL model is not SS better than NG
    y_beta = ranked_performances(:,3);
    [R,P]=corrcoef(x,y_beta);

    fig4_1= figure();
    hold on;

    % plot gamma vs profit
    scatter(x, y_beta,MARKER_SIZE, 'bo');
    text(x + dx/10, y_beta + dy/10 ,labels,'FontSize',ID_TEXT_SIZE);

    % draw the regression line
    lsline;

    % title, labels, font
    title_text = ['Performance VS beta - R = ',num2str(R(1,2))];
    title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);
    ylabel('Beta');
    xlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);
    %axis([-6.5e+03 2e+04 min(y_beta)-max(y_beta)/10, max(y_beta)+max(y_beta)/10]);
    axis([min(x)+min(x) max(x)-min(x) -5 55])
    hold off;
    if SAVE_FIG
        set(gcf, 'PaperUnits', 'centimeters');
        set(gcf, 'PaperPosition', [0 0 PRINT_WIDTH PRINT_HEIGHT]);
        path = '../graphs/stats/performance_cloud/';
        fileName = [path, 'performance_vs_beta_restr',num2str(RESTRICTED)];
        fileName = [fileName,'_',ALGORITHM];
        fileName = [fileName,'_CAP',num2str(CAP),'_nAct',num2str(N_ACTIONS),'.png'];
        print(fig4_1, '-dpng', '-loose', fileName); 
    end
    
    %% FIG 4.2

    % on the y-axis there is beta 
    btr_y_beta = btr_ranked_performances(:,3);

    % calculate regression coefficient R and p-value
    [R,P]=corrcoef(btr_x,btr_y_beta);

    fig4_2 = figure();
    hold on;

    % plot players MLE vs profit
    scatter(btr_x, btr_y_beta,MARKER_SIZE, 'bo');
    text(btr_x + dx, btr_y_beta+dy ,btr_labels,'FontSize',ID_TEXT_SIZE);

    % draw the regression line
    lsline;

    % title, labels, font
    title_text = ['Performance VS beta - R = ',num2str(R(1,2))];
    title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);
    disp(title_text);
    ylabel('Beta');
    xlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);
    axis([min(x)+min(x) max(x)-min(x) -5 55])
    hold off
end

%% FIGURE 5 profit VS alpha VS gamma 
if FIGURES(5)
    fig5 = figure();
    hold on;
    
    y_alpha = ranked_performances(:,2);
    y_gamma = ranked_performances(:,4);
    
    % plot alpha vs profit
    scatter3(y_alpha, y_gamma, x,MARKER_SIZE,'bo');
    %text(y_alpha + dy, y_gamma+dy, x + dx ,labels,'FontSize',ID_TEXT_SIZE);

    % draw the regression line
    %lsline;

    % title, labels, font
    title_text = 'Performance VS alpha VS gamma';
    title(title_text);

    xlabel('Alpha');
    ylabel('Gamma');
    zlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);
    %axis([-6e+03 2e+04 0 1.05]);
    %axis([-0.1 1.1 -0.1 1.1 (min(x)-min(x)*0.1) (max(x)+max(x)*0.1)])
    grid
    hold off;

    if SAVE_FIG
        set(gcf, 'PaperUnits', 'centimeters');
        set(gcf, 'PaperPosition', [0 0 PRINT_WIDTH PRINT_HEIGHT]);
        path = '../graphs/stats/performance_cloud/';
        fileName = [path, 'performance_vs_alpha_vs_gamma_restr',num2str(RESTRICTED)];
        fileName = [fileName,'_',ALGORITHM];
        fileName = [fileName,'_CAP',num2str(CAP),'_nAct',num2str(N_ACTIONS),'.png'];
        print(fig5, '-dpng', '-loose', fileName); 
    end
end
toc