% routine for generating the following figures (and possibly save them)


% 1
% MLE_comparison using CP (errorbars)
% best model (according to avg) vs next 4 models
% 2
% profit V MLE 
% 3
% profit V alpha 
% 4
% profit V gamma
% 5
% profit V alpha V gamma

tic;

close all;                  % there is another close all (to close figs generated by paper_figures()
SIGNIFICANCE_THRESHOLD = 0; % threshold for considering players better than scrambled (0 all players, 0.5 above chance (same as scrabled))
SAVE_FIG = 0;               % flag to handle figure saving on disk (0 does NOT save figures, 1 saves figures)
FIGURES = [1,1,1,1,1];      % boolean vector of flags for figures 
                            % [MLE_comparison with errorbars, profit V MLE, profit V alpha, profit V gamma, profit V alpha V gamma]
                          
alpha_confidence = 0.01;    % 99% confidence
COMPARISON_FACTOR = 0.01;   % tolerance level
CHANCE_THRESHOLD = 0.5;     % probability threshold for chance 
MLE_THRESHOLD = 10;         % consider only players who are RL (arbitrary choice, highest [23.288897]) %TODO check if this still holds after graddesc
P_VALUE_THRESHOLD = 0.05;   % p-value threshold

% markup for figures
dx = 0.25;                  % shift for the player numbers on the datapoints
dy = -0.25;
FONT_SIZE = 30;             
ID_TEXT_SIZE = 20;
PRINT_WIDTH = 80;
PRINT_HEIGHT = 50;
MARKER_SIZE = 100;

RESTRICTED = 0;
ALGORITHM = 'qlearning';
CAP = 25;
N_ACTIONS = 3;

% import scrambled MLE 
[scrambles_number, scrambles] = MLE_SCRAM_importer(RESTRICTED, ALGORITHM, CAP, N_ACTIONS);

% load model results
model = MLE_model_importer(RESTRICTED, ALGORITHM, CAP, N_ACTIONS);

% load performances 
% (0,1 reading offset to avoid string names)
perfs = sortrows(csvread('../results/stats/performances/profit_performances.csv',0,1,[0,1,45,2]),1);

% load performances [playerID model_MLE random_MLE nogamma_MLE p_nog_MLE p_rand_MLE chi_value_random chi_value_nogamma]
performance_fit = paper_figures(0,0);
% populate performances matrix
[playerID model_MLE random_MLE nogamma_MLE p_nog_MLE p_rand_MLE chi_value_random chi_value_nogamma];

% these files are needed to find performance_fit 
% (now generated in paper_figures.m)
% get the players for which the RL model is SS better than NG
full_RL_players = performance_fit(find(performance_fit(:,5) < P_VALUE_THRESHOLD));

% get the random lines from the model
randomMLEs = model(model(:,2) == 0,:);
% other lines are non-random models
model = model(model(:,2) ~= 0,:);

model = [model(:,1:5), model_MLE(:,5:end-1)];

if SIGNIFICANCE_THRESHOLD > 0
    % load players confidence intervals (generated in
    % statistical_test_scrambled.m
    players_CI = csvread('results/stats/players_CI.csv');

    % get the performances subset 
    % players whos lower errorbar is above the threshold
    % (remove players whose MLE is not significative)
    %it's ok to populate dinamycally as it is at most 46 players
    performances = []; 
    for idx = 1:size(perfs,1)
        if players_CI(idx,3) >= SIGNIFICANCE_THRESHOLD
            performances = [performances; perfs(idx,:)];
        end
    end
else
    performances = perfs;
end

% get the number of players
playerAmount = size(performances,1);

% structure to save the p-hat and p-ci 
errorbars = [];

% instantiate structures for statistics
% playerID, profit, MLE best, MLE random, alpha, beta, gamma
stats = [];
nogamma_stats = [];

for idx = 1:playerAmount
    
    % get the player ID
    playerID = performances(idx,1);

    % find player MLEs in results file
    pl_lines = find(model(:,1) == playerID);

    % get the columns [alpha, beta, gamma, MLE]
    current_res = model(pl_lines, 1:end);

    % sort current_res so that the best N models 
    % are available as the first N rows
    current_res = sortrows(current_res,5);

    % get the N best MLE (new version: top N)
    current_res = current_res(1:5,:);

    % store best models alpha beta and gamma and MLE
    abg = current_res(1,2:4);

    % store alpha beta gamma for the alternative models
    alternative_abgs = current_res(2:end,2:4);

    % store best models MLE (avg)
    minMLE = current_res(1,5);

    % get model 1000 MLEs repetitions (exclude the avg MLE col.5)
    best_MLEs = current_res(1,6:end);

    MLE_comparison = zeros(size(current_res(2:end,6:end)));

    randomMLE = randomMLEs(randomMLEs(:,1) == playerID,5);

    for MLE_instance = best_MLEs
        % compare the MLE instance (scalar) 
        % to a matrix of MLES (best N lines)
        % each line summed to itself at each comparison
        % each line is a comparison (sum the line for clopper pearson)
        % comparison__alternative_MLEs is the matrix of MLEs to be compared
        % incremented of 1/100 of each value (COMPARISON_FACTOR)
        comparison__alternative_MLEs = current_res(2:end,6:end) + (current_res(2:end,6:end) * COMPARISON_FACTOR);
        % the comparison sign is > because MLE is better lower 
        % (if the MLE_instance of the best model is higher than 
        % the alternative it means the alternative is better)
        MLE_comparison =  MLE_comparison + +(MLE_instance > comparison__alternative_MLEs);

    end

    % each line is a model
    for jdx = 1:4
        comparison = MLE_comparison(jdx,:);
        [phat,pci] = binofit(sum(comparison),1000*1000,alpha_confidence);

         if pci(1) > CHANCE_THRESHOLD
%             fig = figure();
%             hold on;
%             temp = current_res(2:end,6:end);
%             hist([best_MLEs;temp(jdx,:)].',100);
%             tit_temp = {['player: ', num2str(playerID)], [num2str(pci(1)),' ',num2str(phat),' ',num2str(pci(2))],  num2str(abg),  num2str(alternative_abgs(jdx,:))};
%             title(tit_temp,'FontSize',20);
%             legend({'best','alternative'},'FontSize',20);
%             %axis([0 22 0 1000]);
%             hold off;
%                 if SAVE_FIG
%                     set(gcf, 'PaperUnits', 'centimeters');
%                     set(gcf, 'PaperPosition', [0 0 PRINT_WIDTH PRINT_HEIGHT]);
%                     path = 'graphs/model_MLE_comparison/portfolio/';
%                     fileName = [path, 'player: ', num2str(playerID),'p-hat',num2str(phat), '.png'];
%                     print(fig, '-dpng', '-loose', fileName);
%                 end
            if minMLE < MLE_THRESHOLD
                stats = [stats; playerID, performances(idx,2), minMLE, randomMLE, alternative_abgs(jdx,:)];
            end

            % if player is a nogamma player...
            if sum(find(playerID == full_RL_players)) > 0
                nogamma_stats = [nogamma_stats; playerID, performances(idx,2), minMLE, randomMLE, alternative_abgs(jdx,:)];
            end

        elseif pci(2) < CHANCE_THRESHOLD
            %disp('statistically worse');
        else
            disp('statistically same as best');
        end

        errorbars = [errorbars; phat, pci];
    end

    % get best MLE (OLD version: single MLE)
    %[minMLE, minMLE_idx] = min(current_res(:,4));
    % get alpha, beta and gamma param for best model
    %abg = current_res(minMLE_idx,1:3);

    % store stats
    if minMLE < MLE_THRESHOLD
        stats = [stats; playerID, performances(idx,2), minMLE, randomMLE, abg];
    end

    % if player is a nogamma player...
    if sum(find(playerID == full_RL_players)) > 0
        nogamma_stats = [nogamma_stats; playerID, performances(idx,2), minMLE, randomMLE, alternative_abgs(jdx,:)];
    end
end
    
% close figures generated by paper_figures function
close all;

%% FIGURE 1 MLE comparison using CP (errorbars)
if FIGURES(1)
    % best model (according to avg) vs next 4 models
    figure();
    hold on
    errorbar(1:1:size(errorbars,1),errorbars(:,1),errorbars(:,1)-errorbars(:,2),errorbars(:,3)-errorbars(:,1),'bx');
    plot([-10 size(errorbars,1)+10],[.5 .5],'r-','LineWidth',4)
    axis([-10 200 0 0.75]);%(max(errorbars) + 0.1 * max(errorbars))]);
    hold off
    xlabel('Models');
    ylabel('Probability');
    set(gca,'FontSize',FONT_SIZE);
end

%% FIGURE 2 profit VS MLE
if FIGURES(2)

    % sort players according to performances 
    ranked_performances = sortrows(stats,2);
    %ranked_performances = sortrows(nogamma_stats,2);

    % on the x-axis there is profit
    x = ranked_performances(:,2);

    % on the y-axis there is MLE (best and random)
    y_best = ranked_performances(:,3);
    y_random = ranked_performances(:,4);

    % players ids
    labels = num2str(ranked_performances(:,1));

    % calculate regression coefficient R and p-value
    [R,P]=corrcoef(x,y_best);

    figure();
    hold on;

    % plot players MLE vs profit
    scatter(x, y_best,MARKER_SIZE, 'bo');
    labels_text = text(x + dx, y_best+dy ,labels,'FontSize',ID_TEXT_SIZE);

    % plot line for random MLE (not much info added as all MLE are better)
    %plot(x,y_random,'s-r');

    % draw the regression line
    lsline;

    % title, labels, font
    title_text = ['Performance VS MLE - ', num2str(SIGNIFICANCE_THRESHOLD), ' threshold - R = ',num2str(R(1,2))];
    title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);
    disp(title_text);
    ylabel('Model Fitness (MLE)');
    xlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);

    hold off

    if SAVE_FIG
        set(gcf, 'PaperUnits', 'centimeters');
        set(gcf, 'PaperPosition', [0 0 PRINT_WIDTH PRINT_HEIGHT]);
        path = 'graphs/stats/performance_cloud/portfolio/';
        fileName = [path, 'performance_vs_MLE_t_',num2str(t),'.png'];
        print(fig, '-dpng', '-loose', fileName); 
    end
end

%% FIGURE 3 profit VS alpha
if FIGURES(3)

    % on the y-axis there is alpha 
    y_alpha = ranked_performances(:,5);
    [R,P]=corrcoef(x,y_alpha);

    figure();
    hold on;

    % plot alpha vs profit
    scatter(x, y_alpha,MARKER_SIZE, 'bo');
    text(x + dx/10, y_alpha + dy/10 ,labels,'FontSize',ID_TEXT_SIZE);

    % draw the regression line
    lsline;

    % title, labels, font
    title_text = ['Performance VS alpha - ', num2str(SIGNIFICANCE_THRESHOLD), ' threshold - R = ',num2str(R(1,2))];
    title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);
    ylabel('Alpha');
    xlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);
    axis([-6e+03 2e+04 0.45 1.05]);
    hold off;
    if SAVE_FIG
        set(gcf, 'PaperUnits', 'centimeters');
        set(gcf, 'PaperPosition', [0 0 PRINT_WIDTH PRINT_HEIGHT]);
        path = 'graphs/stats/performance_cloud/portfolio/';
        fileName = [path, 'performance_vs_alpha_t_',num2str(t),'.png'];
        print(fig, '-dpng', '-loose', fileName); 
    end
end

%% FIGURE 4 profit VS gamma
if FIGURES(4)
    % on the y-axis there is gamma 
    % 0 gamma for players whose RL model is not SS better than NG
    y_gamma = zeros(size(x,1),1);
    
    % ia is the index of the RL players in the ranked_performances matrix
    [~,ia,~] = intersect(ranked_performances(:,1),full_RL_players);
    
    % find the gamma != 0 for the full RL players and plot the rest on gamma = 0
    y_gamma(ia) = ranked_performances(ia,7);   
    
    [R,P]=corrcoef(x,y_gamma);

    figure();
    hold on;

    % plot gamma vs profit
    scatter(x, y_gamma,MARKER_SIZE, 'bo');
    text(x + dx/10, y_gamma + dy/10 ,labels,'FontSize',ID_TEXT_SIZE);

    % draw the regression line
    lsline;

    % title, labels, font
    title_text = ['Performance VS gamma - ', num2str(SIGNIFICANCE_THRESHOLD), ' threshold - R = ',num2str(R(1,2))];
    title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);
    ylabel('Gamma');
    xlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);
    axis([-6.5e+03 2e+04 -0.1 1.1]);
    hold off;
    if SAVE_FIG
        set(gcf, 'PaperUnits', 'centimeters');
        set(gcf, 'PaperPosition', [0 0 PRINT_WIDTH PRINT_HEIGHT]);
        path = 'graphs/stats/performance_cloud/portfolio/';
        fileName = [path, 'performance_vs_gamma_t_',num2str(SIGNIFICANCE_THRESHOLD),'.png'];
        print(fig, '-dpng', '-loose', fileName); 
    end
end

%% FIGURE 5 profit VS alpha VS gamma
if FIGURES(5)
    fig = figure();
    hold on;

    % plot alpha vs profit
    scatter3(y_alpha, y_gamma, x,MARKER_SIZE,'bo');
    %text(y_alpha + dy, y_gamma+dy, x + dx ,labels,'FontSize',ID_TEXT_SIZE);

    % draw the regression line
    %lsline;

    % title, labels, font
    title_text = ['Performance VS alpha VS gamma - ', num2str(SIGNIFICANCE_THRESHOLD), ' threshold - R = ',num2str(R(1,2))];
    %title_text = [title_text, '- R2 = ',num2str(R(1,2)^2)];
    %title_text = [title_text,' - p = ',num2str(P(1,2))];
    title(title_text);

    xlabel('Alpha');
    ylabel('Gamma');
    zlabel('Player Performance (profit)');
    set(gca,'FontSize',FONT_SIZE);
    %axis([-6e+03 2e+04 0 1.05]);
    axis([-0.1 1.1 -0.1 1.1 (min(x)-min(x)*0.1) (max(x)+max(x)*0.1)])
    grid
    hold off;

    if SAVE_FIG
        set(gcf, 'PaperUnits', 'centimeters');
        set(gcf, 'PaperPosition', [0 0 PRINT_WIDTH PRINT_HEIGHT]);
        path = 'graphs/stats/performance_cloud/portfolio/';
        fileName = [path, 'performance_vs_gamma_vs_alpha_t_',num2str(SIGNIFICANCE_THRESHOLD),'.png'];
        print(fig, '-dpng', '-loose', fileName); 
    end
end

disp('performance_cloud');
toc